name: Rust Mix Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.12
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Create Environment
      run: conda create --name rustmix python=3.12 -y

    - name: Activate Env
      run: |
        source ~/.profile
        conda activate rustmix

    - name: Install maturin
      run: pip install maturin

    - name: Run build test for rust
      run: maturin develop
